### PR TITLE
jschallenge0 olaouso gizemcdeniz

### PR DESCRIPTION
**Pull request by gizemcdeniz**
javascript inclass added

### CODE REVIEW

**Comment by Halit-Batur** [comment]
@gizemcdeniz PR title is incorrect please check the assignments channel for the correct schema

**Comment by gizemcdeniz** [comment]
> @gizemcdeniz PR title is incorrect please check the assignments channel for the correct schema

edited :) @Halit-Batur

**Comment by louisrli** [comment]
it's in the wrong directory :)

**Comment by louisrli** [comment]
i realized i forgot to mention in the instructions that you should put it in a directory with your name and your partner's name (similar to the other ones)

**Pull request merged**
