### PR TITLE
whereiswaldo fadime94 gizemcdeniz ahmadaljalmoud

### PR DESCRIPTION
**Pull request by fadime94**
We didn't manage to finish the exercises in time for the demo, so we ended up to do this after we had seen the answer. We modified a bit the code because, for us, it is easier to understand this way.

### CODE REVIEW

**Comment by louisrli** [comment]
this has both minesweeper and wheres waldo :)

**Comment by fadime94** [comment]
I don't understand what I have to do. I put in different folders both exercises

**Comment by louisrli** [comment]
yeah but this PR is titled whereiswaldo, not minesweeper. so minesweeper has to go 🙂

**Comment by fadime94** [comment]
I hope now it is okay. :( I thought I wrote it before. So, now I went to
edit it. If this doesn't work either, I really don't know what to do

Il giorno mar 1 set 2020 alle ore 14:58 Louis Li <notifications@github.com>
ha scritto:

**Comment by louisrli** [comment]
this is supposed to be whereiswaldo, but you need to use git branch to remove the minesweeper file so that when i go to "files changed", i only see one of the files. does that make sense?

**Comment by fadime94** [comment]
I deleted, should I create a new branch for the other exercise?

**Comment by louisrli** [comment]
Depends on if you or your partner is PRing the other exercise, but it's up to you if you want to practice branch-making :) otherwise this LGTM

**Pull request merged**
