### PR TITLE
events-calculator-challenge Jamil Yaman

### PR DESCRIPTION
**Pull request by YamanSammani**
Kindly find Jamil and Yaman calculator exercise :) into Class 8
Add Yaman Personal webPage into Class 2

### CODE REVIEW

**Comment by louisrli** [comment]
PR title

**Comment by YamanSammani** [comment]
Sorry, Updated :)

**Comment by louisrli** [comment]
hmm normally i wouldn't allow both class2 and class8 in the same PR but since you put it in the PR description...i'll let it pass this time. but next time you have to git branch and split it :)

**Comment by YamanSammani** [comment]
I was trying to PR them separately 😅 , but for some reason ( due to my extra professionality using Github 💪🏽), they're pushed together 🙈. 
Thanks and well noted.

**Pull request merged**
