### PR TITLE
assignment2_class3

### PR DESCRIPTION
**Pull request by olaouso**

### CODE REVIEW

**Comment by louisrli** [comment]
the PR name should be as specified in the assignment 🙂

**Comment by olaouso** [comment]
> the PR name should be as specified in the assignment 🙂

sorry, so I should revise the two PRs

**Comment by olaouso** [comment]
I edited the pull request commit :)

**Comment by louisrli** [comment]
ah, i'm referring to this one

image

we use this for grading :)

**Comment by olaouso** [comment]
Hi Louis 
I solved the name issue in class3 pull request

**Comment by louisrli** [comment]
Hi Ola, the name of the PR in the Github website should be `jschallenge1 olaouso ssinikoglu` (not the commit name -- they are different).

Now there are also a lot of extra files so you can practice using git branch to cut out just the class3 part for this PR :)

**Pull request merged**
