### PR TITLE
Blog mockup design. ihab-sensei, Luey-A

### PR DESCRIPTION
**Pull request by ihab-sensei**
please accept my pull request

### CODE REVIEW

**Comment by Halit-Batur** [comment]
@ihab-sensei can you please change the dir name so it start's with your name example : Ihab-Luey

**Comment by ihab-sensei** [comment]
Of course. i didn't put our names since it's inside the dir that have our names on it

**Comment by Halit-Batur** [comment]
@ihab-sensei Still not fixed :). you added another layer of Dir, I asked you to change the main Dir name to Ihab-Luey

**Comment by Halit-Batur** [comment]
@ihab-sensei good work !

**Pull request merged**
