### PR TITLE
Strings-arrays-challenges raycodes-2020 majdajroudi

### PR DESCRIPTION
**Pull request by raycodes-2020**
That's our pull request for Strings-arrays-challenges

### CODE REVIEW

**Comment by louisrli** [comment]
can you please reread the assignment for the PR name. it should also be majd's github username, and there's a typo in your github username

**Comment by raycodes-2020** [comment]
yeah sure ,  I just saw the last pull requests and they put majd only on
files so I thought that is his github name .

**Comment by louisrli** [comment]
can you ask him what his github name is and fix it?

**Comment by raycodes-2020** [comment]
yes I have fixed it now
for today calculator I have finished all the JavaScript but no styling
 should I pull request alone or mix my work with cigan and Mohammed .

**Comment by raycodes-2020** [comment]
I have fixed it now

**Comment by louisrli** [comment]
this PR has two files not from the intended class. can you use git branch to PR just the files you want?

**Comment by raycodes-2020** [comment]
can you check please if it's fixed now ,

**Comment by louisrli** [comment]
nice work ray!

**Pull request merged**
