### PR TITLE
portofilo-website Jamil-Bailony, blog-page Jamil-Bailony khaldoon9kh

### PR DESCRIPTION
**Pull request by Jamil-Bailony**

### CODE REVIEW

**Comment by Halit-Batur** [comment]
@Jamil-Bailony please fix the following 
1- PR title should be blog-exercise <your github name> <khaldoon's github name> (since I can see there's class 3 related files included in the PR)
2- The dir name is incorrect for the class 3 it should be Jamil-Khaldoon

**Comment by Jamil-Bailony** [comment]
Hey @Halit-Batur,
I have renamed the folder and updated the PR's title. Please tell me if there is anything to do.

**Comment by Halit-Batur** [comment]
@Jamil-Bailony the PR title is still not following the schema

**Comment by Jamil-Bailony** [comment]
@Halit-Batur,
I have updated the PR's title.

Thank you very much.

**Comment by Halit-Batur** [comment]
@Jamil-Bailony Good Work ! but please next time make sure to make separate PRs

**Pull request merged**
