### PR TITLE
why-we-code knargocer fadime94 

### PR DESCRIPTION
**Pull request by knargocer**
Made the site responsive. Our group consists of me and Fadime.

### CODE REVIEW

**Comment by Halit-Batur** [comment]
@knargocer the PR title is wrong can you please follow the schema I sent on the assignments channel ?

**Comment by knargocer** [comment]
Sorry, I edited it,  is this one correct?

**Comment by Halit-Batur** [comment]
@knargocer it's correct but the files should be inside a dir named knar-fadime and that dir should be inside class3 dir

**Comment by knargocer** [comment]
I changed it, Can you please check now?

**Comment by louisrli** [comment]
there is a file, `class3/style.css`, that should not be there -- there should only be files in the directory for your group

**Comment by knargocer** [comment]
I tried to remove the extra files, I hope it worked this time.

**Pull request merged**
