### PR TITLE
movie project ibrahim sule

### PR DESCRIPTION
**Pull request by ibrahimaljarad**

### CODE REVIEW

**Comment by halitbatur** [comment]
@ibrahimaljarad the oop javascript file is empty , could you please fix that ?

**Comment by ibrahimaljarad** [comment]
file fixed, can you check again please.

**Comment by halitbatur** [comment]
@ibrahimaljarad lgtm thanks for the quick fix

**Comment by halitbatur** [comment]
@ibrahimaljarad there's just one more thing in your fileschancged you have changed the readme.md file that we have at the top level directory could you fix that too ?

**Comment by louisrli** [comment]
ibrahim could you update this pr please

**Pull request closed without merging**
