### PR TITLE
jschallenge1 ihab-sensei Jamil-Bailony

### PR DESCRIPTION
**Pull request by ihab-sensei**

### CODE REVIEW

**Comment by ihab-sensei** [comment]
P.S. This PR is for the last two assignments.

**Comment by louisrli** [comment]
please double check files changed and see if you can see why this PR has a mistake :)

**Comment by ihab-sensei** [comment]
There should be two PRs I guess, I wanted to make them separate but Github automatically joins them.

**Comment by louisrli** [comment]
use git branch

23 Tem 2020 Per, saat 11:24 tarihinde Ihab Almashhadani <
notifications@github.com> şunu yazdı:

**Comment by ihab-sensei** [comment]
Well... that was an interesting thing to tinker with XD

**Comment by louisrli** [comment]
ha. I'm impressed you did it though, it's not easy! but that's why we practice PRing. good work.

**Pull request merged**
