### PR TITLE
responsive-exercise bertacsevercan knargocer

### PR DESCRIPTION
**Pull request by bertacsevercan**
I added the js file to the folder.

### CODE REVIEW

**Comment by bertacsevercan** [comment]
I added the responsive website by mistake, I thought I can open 2 different PRs.

**Comment by louisrli** [comment]
i still see the responsive site class4 here. my tip here is that you probably want to be using git branch, git checkout, and then deleting files

so for example, if your goal is:
* master branch will have class4 and class5
* you will pull request a new branch called `class5only`

```
git checkout -b class5only
# delete the files for class4
# push
# create a new pull request
```

**Comment by bertacsevercan** [comment]
Changed this to responsive-exercise since it has the file in it.

**Comment by louisrli** [comment]
nice work. good usage of git branch. most people mess this up the first time i ask them to do it, i'm impressed by your resourcefulness!

**Pull request merged**
